GET http://localhost:8000/products HTTP/1.1

###
POST http://localhost:8000/products/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=key
&quantity=50

###
DELETE http://localhost:8000/products/614f409f000aadfbb886edfa HTTP/1.1

###
POST  http://localhost:8000/products/614f392f40f86aa586e96d6d/update_quantity/?number=100 HTTP/1.1
